version: '3.1'

services:

  database:
    image: postgres:14.0-alpine
    container_name: database
    ports:
      - "8080:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=username
      - POSTGRES_DB=database


#volumes:
#  volumedataholder:
#  postgres_data:
#    driver: local