version: '3.1'

services:

  database:
    image: postgres:14.0-alpine
    container_name: databaseKanbanBoard
    ports:
      - "8090:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=username
      - POSTGRES_DB=database
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: